{% set name = "segment-anything" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/segment-anything-py/segment-anything-py-{{ version }}.tar.gz
  sha256: deea07eeb9f473015472a4bb0d196c327356b7d7224e0179da6a631f5ad3b707

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pytorch >=1.7
    - torchvision >=0.8

test:
  imports:
    - segment_anything
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opengeos/segment-anything
  summary: An unofficial Python package for Meta AI's Segment Anything Model
  description: An unofficial Python package for Meta AI's Segment Anything Model
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
